In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [16]:
df=pd.read_csv(r"C:\Users\ASUS\Desktop\DATA ANALYST DATA SCIENCE\pca_ex.csv")

In [17]:
df

Feature  Ex1  Ex2  Ex3  Ex4
0      x1    4    8   13    7
1      x2   11    4    5   14

In [20]:
pca_X=df.iloc[:,1:].values

In [21]:
pca_X

array([[ 4,  8, 13,  7],
       [11,  4,  5, 14]], dtype=int64)

In [22]:
from sklearn.decomposition import PCA

In [32]:
pca=PCA(n_components=2)

In [33]:
x=pca.fit(pca_X)

In [34]:
x

PCA(n_components=2)

In [35]:
bc_pca=pca.fit_transform(pca_X)

In [36]:
bc_pca1=pca.transform(pca_X)

In [37]:
np.round(bc_pca1,2)

array([[ 6.67,  0.  ],
       [-6.67, -0.  ]])

In [38]:
pca.explained_variance_ratio_

array([1.0000000e+00, 2.4928891e-33])

In [39]:
print(bc_pca)

[[ 6.67083203e+00  3.33066907e-16]
 [-6.67083203e+00  3.33066907e-16]]


In [31]:
13/21

0.6190476190476191

In [41]:
m=np.array([[137,76,107,182],[76,80,124,112],[107,124,194,161],[182,112,161,245]])

In [42]:
eigen_vals,eigen_vecs=np.linalg.eig(m)

In [46]:
print(eigen_vals)

[ 5.68875487e+02  8.71245135e+01  1.30327097e-14 -6.21423639e-15]


In [47]:
print(eigen_vecs)

[[-0.45678259  0.45835516  0.70364704  0.27625562]
 [-0.3476681  -0.35915276 -0.32637146 -0.80445316]
 [-0.51780257 -0.68994515  0.28701898  0.49915261]
 [-0.63431621  0.4299948  -0.56212332 -0.16548302]]
